### ISSUE TITLE
Find Eventual Safe States problem from Leetcode in C++

### ISSUE THREAD

**Issue by Amisha328** [nishchalgv1/leetcode_solutions#3]
**Problem Description link:** https://leetcode.com/problems/find-eventual-safe-states/description/

**Comment by Amisha328** [comment]
Hi @nishchalgv1,

I want to contribute to this problem, please assign this issue to me under **Hacktoberfest24**.

**Comment by nishchalgv1** [comment]
Make sure you start this repo and you can start working on it.

**Comment by Amisha328** [comment]
Hi @nishchalgv1,

can you please merge my PR.
